version: "3"
services:
  api: 
    image: fusion
    build: ../../../../ 

    ports:
      - ${PORT-3000}

    links:
      - db

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:-3000}
      
  db:
    image: postgres

    ports:
      - "5432:5432"

    volumes:
      - ../postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
